export const DISNEY_WORDS = [
  'Mickey',
  'Minnie',
  'Donald',
  'Daisy',
  'Dingo',
  'Pluto',
  'Pat Hibulaire',
  'Clarabelle',
  'Horace',
  'Riri',
  'Fifi',
  'Loulou',
  'Picsou',
  'Max',
  'Oswald',
  'PJ',
  'Clarisse',
  'Mortimer',
  'La fée Clochette',
  'Vidia',
  'La Reine Clarion',
  'Flora',
  'Pâquerette',
  'Pimprenelle',
  'La Fée Bleue',
  'Marraine la Bonne Fée',
  'Mama Odie',
  'Grand-mère Fa',
  'La Marieuse',
  'La Reine Grimhilde',
  'Héra',
  'Jack Skellington',
  'Oogie Boogie',
  'Am, Stram & Gram',
  'Blanche-Neige',
  'Cendrillon',
  'Aurore',
  'Ariel',
  'Belle',
  'Jasmine',
  'Pocahontas',
  'Mulan',
  'Tiana',
  'Raiponce',
  'Mérida',
  'Vaiana',
  'Anna',
  'Elsa',
  'Kida',
  'Raya',
  'Asha',
  'Mirabel',
  'Isabela',
  'Luisa',
  'Esmeralda',
  'Jane',
  'Wendy',
  'Lily la Tigresse',
  'Belle Marianne',
  'Le Prince Florian',
  'Le Prince Henri',
  'Le Prince Philippe',
  'Le Prince Eric',
  'La Bête / Prince Adam',
  'Naveen',
  'Flynn Rider',
  'Hans',
  'Kristoff',
  'John Smith',
  'Aladdin',
  'Shang',
  'Tarzan',
  'Kuzco',
  'Pacha',
  'Milo',
  'Jim Hawkins',
  'Simba',
  'Mufasa',
  'Scar',
  'Nala',
  'Sarabi',
  'Kiara',
  'Rafiki',
  'Zazu',
  'Timon',
  'Pumbaa',
  'Ed',
  'Dumbo',
  'Timothée',
  'Bambi',
  'Pan-Pan',
  'Fleur',
  'Duchesse',
  'Berlioz',
  'Toulouse',
  'Marie',
  'Thomas O’Malley',
  'Pongo',
  'Perdita',
  'Patch',
  'Roger Radcliff',
  'Anita Radcliff',
  'Winnie l’Ourson',
  'Jean-Christophe',
  'Porcinet',
  'Tigrou',
  'Bourriquet',
  'Coco Lapin',
  'Mitaine',
  'Rhino',
  'Petit Gourou',
  'Maman Gourou',
  'Lumpy',
  'Polochon',
  'Sébastien',
  'Eurêka',
  'Le Roi Triton',
  'Abu',
  'Rajah',
  'Tapis volant',
  'Le Génie',
  'Le Sultan',
  'Jafar',
  'Iago',
  'Tantor',
  'Tok',
  'Kala',
  'Kerchak',
  'Clayton',
  'Sabor',
  'Mowgli',
  'Bagheera',
  'Baloo',
  'Kaa',
  'Le Roi Louie',
  'Shere Khan',
  'Robin des Bois',
  'Petit Jean',
  'Frère Tuck',
  'Dame Gertrude',
  'Triste Sire',
  'Le Prince Jean',
  'Le Shérif de Nottingham',
  'Niquedouille',
  'Jaq',
  'Gus',
  'Lucifer',
  'l’Armoire',
  'Big Ben',
  'Lumière',
  'Mme Samovar',
  'Zip',
  'Philibert',
  'Maurice',
  'Plumette',
  'Souillon',
  'Meeko',
  'Flit',
  'Grand-mère Feuillage',
  'John Ratcliffe',
  'Percy',
  'Maximus',
  'Pascal',
  'Mushu',
  'Cri-Kee',
  'Koda',
  'Stitch',
  'Jumba',
  'Pikly',
  'Lilo',
  'Nani',
  'Tuk Tuk',
  'Sisu',
  'Hei Hei',
  'Pua',
  'Pegasus',
  'Philovtète',
  'Maléfique',
  'Cruella d’Enfer',
  'Madame Mim',
  'Edgar',
  'Ratigan',
  'Ursula',
  'Flotsam & Jetsam',
  'Gaston',
  'Le Fou',
  'Frollo',
  'Hadès',
  'Peine',
  'Panique',
  'Shan-Yu',
  'Yzma',
  'Kronk',
  'Gantu',
  'John Silver',
  'Docteur Facilier',
  'Mère Gothel',
  'Sa Sucrerie',
  'Guimauve',
  'Dawn Bellwether',
  'Tamatoa',
  'Kakamoras',
  'Namaari',
  'Mignifico',
  'Merlock',
  'Jiminy Cricket',
  'Figaro',
  'Roger Rabbit',
  'Roxanne',
  'Powerline',
  'Rox',
  'Rouky',
  'Taram',
  'Basil',
  'Oliver',
  'Quasimodo',
  'Hercules',
  'Lewis Robinson',
  'Ralph la Casse',
  'Hiro',
  'Baymax',
  'Nick Wilde',
  'Judy Hopps',
  'Bruno',
  'Clopin',
  'Jean Darling',
  'Michel Darling',
  'Nana',
  'Elliot',
  'Bernard',
  'Bianca',
  'Volt',
  'Félix',
  'Olaf',
  'Sven',
  'Bruni',
  'Ray',
  'Tala',
  'Gazelle',
  'Mr Big',
  'Capitaine Amélia',
  'Truc & Muche',
  'Razmotte',
  'Morph',
  'BEN',
  'Archimède',
  'Tweedle Dee & Tweedle Dum',
  'Le Chapelier',
  'Le Chat du Cheshire',
  'Le Lapin Blanc',
  'Le Lièvre de Mars',
]
